fresh_shop/carts/urls.py
from django.conf.urls import url
from carts import views



urlpatterns = [

    url(r'^cart/', views.cart, name='cart'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^show_cart_count/', views.show_cart_count, name='show_cart_count'),
    url(r'^check_inventory/', views.check_inventory, name='check_inventory'),
    url(r'^change_cart/', views.change_cart, name='change_cart'),
    url(r'^del_cart/(\d+)/', views.del_cart, name='del_cart'),
    url(r'^change_all_cart/',views.change_all_cart,name='change_all_cart'),
]

fresh_shop/fresh_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.views.static import serve

from fresh_shop import settings
from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT
from goods import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^api/goods/', include('goods.urls')),
    url(r'^static/(?P<path>.*)$', serve, {"document_root": settings.STATICFILES_DIRS[0]}),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),

    url(r'^$', views.index),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

fresh_shop/goods/urls.py
from django.conf.urls import url
from goods import views
# from rest_framework.routers import SimpleRouter
# router = SimpleRouter()
# router.register('goods', views.Goods)


urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^detail/(\d+)/', views.detail, name='detail'),
    url(r'^list/(\d+)/', views.list, name='list'),
    url(r'^search_list/', views.search_list,name='search_list'),
]

# urlpatterns += router.urls

fresh_shop/order/urls.py
from django.conf.urls import url
from order import views



urlpatterns = [

    url(r'^place_order/',views.place_order, name='place_order'),
    url(r'^user_center_order/',views.user_center_order, name='user_center_order'),
    url(r'^make_order/', views.make_order, name='make_order'),
]

fresh_shop/user/urls.py
from django.conf.urls import url
from user import views



urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^register/', views.register, name='register'),
    url(r'^user_center_info/', views.user_center_info, name='user_center_info'),
    url(r'^user_center_site/',views.user_center_site, name='user_center_site',)

]

fresh_shop/carts/models.py
from django.db import models

# Create your models here.
from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

fresh_shop/carts/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from carts.models import ShoppingCart
from goods.models import Goods


def cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        data = []
        if session_goods:
            for se_goods in session_goods:
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                nums = se_goods[1]
                is_select = se_goods[2]
                price = goods.shop_price * se_goods[1]
                data.append([goods,nums, price,is_select])
        return render(request, './cart.html',{'goods_all': data})
    if request.method == 'POST':
        keyword = request.POST.get('keyword')
        if keyword:
            return HttpResponseRedirect(reverse('goods:search_list')+'?keyword={}'.format(keyword))
        else:
            session_goods = request.session.get('goods')
            data = []
            if session_goods:
                for se_goods in session_goods:
                    goods = Goods.objects.filter(pk=se_goods[0]).first()
                    nums = se_goods[1]
                    is_select = se_goods[2]
                    price = goods.shop_price * se_goods[1]
                    data.append([goods, nums, price, is_select])
            return render(request, './cart.html', {'goods_all': data})


def add_cart(request):
    if request.method == 'POST':
        #保存到session中
        #1.获取前端ajax提交的goode_id,num
        # 2.组装存储到session的数据
        goods_id = request.POST.get('goods_id')
        nums = request.POST.get('nums')
        # 组装存储的结构
        goods_list = [int(goods_id), int(nums), 1]
        #判断session中是否保存了goods
        session_goods = request.session.get('goods')
        if session_goods:
            # 添加或者修改
            flag = False
            for goods in session_goods:
                if goods[0] == int(goods_id):
                    goods[1] += int(nums)
                    flag = True
            if not flag:
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            goods_count = len(session_goods)
        else:
            request.session['goods'] = [goods_list]
            goods_count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功','goods_count':goods_count})

def show_cart_count(request):
    if request.method == 'POST':
        try:
            session_goods = request.session.get('goods')
            goods_count = len(session_goods)
        except:
            goods_count = 0
        return JsonResponse({'code':200, 'msg':'请求成功','goods_count':goods_count})

def check_inventory(request):
    if request.method == 'POST':
        goods_id = request.POST.get('goods_id')
        goods = Goods.objects.get(pk=goods_id)
        goods_nums = goods.goods_nums
        return JsonResponse({'code':200, 'msg':'请求成功','goods_nums':goods_nums})


def change_cart(request):
    if request.method == 'POST':

        goods_id = int(request.POST.get('goods_id'))
        is_select = request.POST.get('is_select')
        nums = request.POST.get('nums')
        session_goods = request.session.get('goods')
        for goods in session_goods:
            if goods_id == goods[0]:
                goods[1] = int(nums) if nums else goods[1]
                if is_select:
                    is_selects = int(is_select)
                    goods[2] = is_selects
        request.session['goods'] = session_goods
        return JsonResponse({'code':200, 'msg':'请求成功'})

def del_cart(request,id):
    if request.method == 'GET':
        user_id = request.session.get('user_id')
        if user_id:
            ShoppingCart.objects.filter(user_id=user_id,goods_id=id).delete()
        session_goods = request.session.get('goods')
        for goods in session_goods:
            if goods[0] == int(id):
                session_goods.remove(goods)
        request.session['goods'] = session_goods
        return HttpResponseRedirect(reverse('carts:cart'))

def change_all_cart(request):
    if request.method == 'POST':
        is_select = request.POST.get('is_select')
        session_goods = request.session.get('goods')
        for goods in session_goods:
            goods[2] = int(is_select)
        request.session['goods'] = session_goods
        return JsonResponse({'code': 200, 'msg': '请求成功'})

fresh_shop/templates/cart.html
{% extends 'base_main.html' %}
{% block title %}
天天生鲜-购物车
{% endblock %}


{% block search %}
<div class="search_bar clearfix">
	<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
	<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
	<div class="search_con fr">
        <form action="" method="post">
         {% csrf_token %}
		<input type="text" class="input_text fl" name="keyword" placeholder="搜索商品">
		<input type="submit" class="input_btn fr" name="" value="搜索">
        </form>
	</div>
</div>
{% endblock %}

{% block contend %}
    <div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	{% if goods_all %}
	{% for goods in goods_all %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" class="check01" {% if goods.3 %} checked {% endif %} onchange="change_box({{ goods.0.id }})" id="box_{{ goods.0.id }}"></li>
		<li class="col02"><img {% if goods.0.goods_desc %} src="{{ goods.0.goods_front_image }}" {% endif %} src="/media/{{ goods.0.goods_front_image }}"></li>
		<li class="col03" style="margin-top:0;">{{ goods.0.name }}<br><em>{{ goods.0.shop_price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05 shop_price">{{ goods.0.shop_price }}</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" onclick="add_cart({{ goods.0.id }})">+</a>
				<input type="text" class="num_show fl" value="{{ goods.1 }}" id="goods_cart_{{ goods.0.id }}">
				<a href="javascript:;" class="minus fl" onclick="sub_cart({{ goods.0.id }})">-</a>
			</div>
		</li>
		<li class="col07">{{ goods.2 }}元</li>
		<li class="col08"><a href="{% url 'carts:del_cart' goods.0.id %}">删除</a></li>
	</ul>
	{% endfor %}
	{% endif %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked="" id="selectAll"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="/order/place_order/">去结算</a></li>
	</ul>
	<script>
		function priceTotal(){
			var checkboxs = $('.check01');
			var shop_prices = $('.shop_price');
			var counts = $('.num_show');
			var subtotals = $('.col07');
			var totalCount = 0;
			var totalPrice = 0;
			for (var i=0;i<checkboxs.length;++i) {
				if (checkboxs[i].checked){
					var count = parseInt($(counts[i]).val());
					totalCount += count
					var price = parseInt($(shop_prices[i]).text())
					subtotal = price * count
					$(subtotals[i]).text(subtotal)
					totalPrice += subtotal
				}
			}
			$('.total_count em').text(totalCount);
			$('.col03 b').text(totalCount);
			$('.col03 em').text(totalPrice.toFixed(2));
		}
		priceTotal()
		function add_cart(goods_id){
			var v = $("#goods_cart_" + goods_id).val();
			var new_value = parseInt(v) + 1;
			$("#goods_cart_" + goods_id).val(new_value);
			cart_ajax(goods_id)

		}
		function sub_cart(goods_id){
			var v = $("#goods_cart_" + goods_id).val();
			if(v > 1){
				var new_value = parseInt(v) - 1;
			$("#goods_cart_" + goods_id).val(new_value);
			cart_ajax(goods_id)
			}
		}
		function cart_ajax(goods_id){
			var nums = $("#goods_cart_" + goods_id).val();
			var csrf = $('input[name="csrfmiddlewaretoken"]').val();
			$.ajax({
				url:'/carts/change_cart/',
				type:'POST',
				dataType:'json',
				headers:{'X-CSRFToken': csrf},
				data:{'goods_id':goods_id, 'nums':nums},
				success: function(data){
					priceTotal()
				},
				error: function(data){
					alert('失败')
				}
			})
		}
		function change_box(goods_id){
			if ($('#box_' + goods_id)[0].checked){
				is_select = 1;
			}else{
				is_select = 0
			}
			var csrf = $('input[name="csrfmiddlewaretoken"]').val();
			$.ajax({
				url:'/carts/change_cart/',
				type:'POST',
				dataType:'json',
				data:{'goods_id':goods_id,'is_select':is_select},
				headers:{'X-CSRFToken': csrf},
				success:function(data){
					if (data.code==200){
						priceTotal()
						change_all_select()
					}
				},
				error: function(data){
					alert('改变失败')
				},
			})
		}
		$('#selectAll').on('click', function(evt) {
			$('.check01').prop('checked', evt.target.checked);
			if (evt.target.checked){
				is_select=1
			}else{is_select=0};
			var csrf = $('input[name="csrfmiddlewaretoken"]').val();
			$.ajax({
				url:'/carts/change_all_cart/',
				type:'POST',
				dataType:'json',
				data:{'is_select':is_select},
				headers:{'X-CSRFToken': csrf},
				success:function(data){
					if (data.code==200){
						priceTotal()

					}
				},
				error: function(data){
					alert('全选失败')
				},
			})
		});
		function change_all_select(){
			var checkboxs = $('.check01')
			var flag = true
			for (var i=0;i<checkboxs.length;i++) {
				if (checkboxs[i].checked){
					console.log(1)
				}else{flag=false}
			}
			$('#selectAll').attr('checked',flag)
		}
		change_all_select()



	</script>




{% endblock %}

fresh_shop/templates/detail.html
{% extends 'base_main.html' %}

{% block title %}
天天生鲜-商品详情
{% endblock %}







{% block contend %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for category,id in data.items %}
					<li><a href="{% url 'goods:list' id %}" class="fruit">{{ category }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/goods/index/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img {% if goods.goods_desc %} src="{{ goods.goods_front_image }}" {% endif %} src="/media/{{ goods.goods_front_image }}" style="height:350px;width:350px"></div>

		<div class="goods_detail_list fr">
			<input type="text" style="display:none" value="{{ goods.goods_nums }}" id="inventory">
			<h3>{{ goods.name }}</h3>
			<p>{{ goods.goods_brief }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="shopprice">{{ goods.shop_price }}</em>元</span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1" id="num_show" onchange="num_show({{ goods.id }})">
					<a href="javascript:;" class="add fr" id="addfr" onclick="add_fr({{ goods.id }})">+</a>
					<a href="javascript:;" class="minus fr" id="minusfr">-</a>
				</div>
			</div>
			<div class="total">总价：<em id="total_price">{{ goods.shop_price }}</em>元</div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart" onclick="add_to_cart({{ goods.id }})">加入购物车</a>
			</div>
		</div>
	</div>
	{% csrf_token %}
	<script>
		function add_to_cart(id){
			var nums = $('#num_show').val();
			var csrf = $('input[name="csrfmiddlewaretoken"]').val();
			$.ajax({
				url:'/carts/add_cart/',
				data:{'goods_id':id,'nums':nums},
				type:'POST',
				dataType:'json',
				headers:{'X-CSRFToken': csrf},
				success: function(data){
					if (data.code == 200){
						$('#show_count').text(data.goods_count)
					}

				},
				error: function(data){
					alert('添加购物车失败')
				}

			})

		}
	</script>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="/static/images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="/static/images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_desc | safe }} </dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}


{% block js2 %}
	<div class="add_jump"></div>
	<script type="text/javascript" src="/static/js/show-good.js"></script>
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script>
		function goodPriceTotal(){
			var value = $('#num_show').val();
			var num = parseInt(value);
			var shop_price = parseFloat($('#shopprice').text());
			var total_price = (num * shop_price).toFixed(2);
			$('#total_price').text(total_price);
		}
		function check_inventory(id){
			var csrf = $('input[name="csrfmiddlewaretoken"]').val();
			$.ajax({
				url:'/carts/check_inventory/',
				type:'POST',
				dataType:'json',
				data:{'goods_id':id},
				headers:{'X-CSRFToken': csrf},
				success:function(data){
					inventory = data.goods_nums;
					$('#inventory').val(inventory)

				},
				error:function(data){
					alert('请求库存失败')
				},
			});


		}
		function add_fr(id){
			var value = $('#num_show').val();
			var num = parseInt(value);
			check_inventory(id);
			var inventory = parseInt($('#inventory').val());
			if (num<200 & num<inventory){
				num += 1
			};
			$('#num_show').val(num);
			goodPriceTotal();
		}
		$('#minusfr').on('click',function(){
			var value = $('#num_show').val();
			var num = parseInt(value);
			if (num>0){
				num -= 1
			}
			$('#num_show').val(num)
			goodPriceTotal()
		})
		function num_show(id){
			var value = $('#num_show').val();
			var regex = /[1-9]\d*.?\d*/;
			if (regex.test(value)) {
				var num = parseInt(value);
				check_inventory(id)
				var inventory = parseInt($('#inventory').val());
				if (num>inventory){
					var num = inventory
				};
				$('#num_show').val(num)
				if (0<num&num<200){
					goodPriceTotal();
				}else{
					$('#num_show').val(200);
					goodPriceTotal();
				}
			}else{
				$('#num_show').val(1)
				goodPriceTotal();
			}
		}


	</script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						<!--$('#show_count').html(2);-->
					});

			});
		})
	</script>
{% endblock %}

	

fresh_shop/templates/index.html
{% extends 'base_main.html' %}
{% block title %}
天天生鲜-首页
{% endblock %}

{% block js %}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}






{% block contend %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="/goods/index/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>
	{% for goods,value in goods_category.items %}

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ value.0.category.id }}">{{ goods }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="{% url 'goods:list' value.0.category.id %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{ value.0.category.category_front_image}}"></div>
			<ul class="goods_list fl">
				{% for good in value  %}s
				<li>
					<h4><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></h4>
					<a href="{% url 'goods:detail' good.id %}"><img src="/media/{{ good.goods_front_image }}"></a>
					<div class="prize">{{ good.shop_price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endfor %}

{% endblock %}

{% block js2 %}
	<script type="text/javascript" src="/static/js/slide.js"></script>
	<script type="text/javascript" src="/static/js/show-good.js"></script>
	<script type="text/javascript">
		<!--BCSlideshow('focuspic');-->
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

fresh_shop/templates/list.html
{% extends 'base_main.html' %}

{% block title %}
天天生鲜-商品列表
{% endblock %}

{% block contend %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				{% csrf_token %}
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for category,id in data.items %}
					<li><a href="{% url 'goods:list' id %}" class="fruit">{{ category }}</a></li>
					{% endfor %}
					<!--<li><a href="#" class="seafood">海鲜水产</a></li>-->
					<!--<li><a href="#" class="meet">猪牛羊肉</a></li>-->
					<!--<li><a href="#" class="egg">禽类蛋品</a></li>-->
					<!--<li><a href="#" class="vegetables">新鲜蔬菜</a></li>-->
					<!--<li><a href="#" class="ice">速冻食品</a></li>-->
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/goods/index/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
	{% csrf_token %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="/static/images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="/static/images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for good in page %}
				<li>
					<a href="{% url 'goods:detail' good.id %}"><img {% if good.goods_desc %} src="{{ good.goods_front_image }}" {% endif %} src="/media/{{ good.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.shop_price }}</span>
						<span class="unit">500g</span>
						<a href="javascript:;" class="add_goods" title="加入购物车" onclick="add_to_cart({{ good.id }})"></a>
					</div>
				</li>
				{% endfor %}
				<!--<li>-->
					<!--<a href="#"><img src="/static/images/goods/goods004.jpg"></a>-->
					<!--<h4><a href="#">吐鲁番梨光杏</a></h4>-->
					<!--<div class="operate">-->
						<!--<span class="prize">￥5.50</span>-->
						<!--<span class="unit">5.50/500g</span>-->
						<!--<a href="#" class="add_goods" title="加入购物车"></a>-->
					<!--</div>-->
				<!--</li>-->


			</ul>

			<div class="pagenation">
				{% if page.has_previous %}
				<a href="{% url 'goods:list' category_id %}?page={{ page.previous_page_number }}">上一页</a>
				{% endif %}
				{% for i in page.paginator.page_range %}
				<a href="{% url 'goods:list' category_id %}?page={{ i }}" class="active">{{ i }}</a>
				{% endfor %}
				{% if page.has_next %}
				<a href="{% url 'goods:list' category_id %}?page={{ page.next_page_number }}">下一页></a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}


{% block js2 %}
<script type="text/javascript" src="/static/js/show-good.js"></script>
<script>
		function add_to_cart(id){
			var nums = 1
			var csrf = $('input[name="csrfmiddlewaretoken"]').val();
			$.ajax({
				url:'/carts/add_cart/',
				data:{'goods_id':id,'nums':nums},
				type:'POST',
				dataType:'json',
				headers:{'X-CSRFToken': csrf},
				success: function(data){
					if (data.code == 200){
						$('#show_count').text(data.goods_count)
					}
				},
				error: function(data){
					alert('添加购物车失败')
				}

			})

		}
	</script>
{% endblock %}

	